### ISSUE TITLE
Open the menu in window mode

### ISSUE THREAD

**Issue by razvn** [tkint/kyro#1]
in browser windowed mode when the menu is hidden clicking on the button to show it does not show the menu.
![Screenshot 2024-02-01 at 10 22 56](https://github.com/tkint/kyro/assets/745873/2b0b191b-9aca-48dd-9f91-acc3e2f7804d)

**Comment by tkint** [comment]
Hello,

It has been fixed in 9ee384cdbc55ceef34e5f5dd9d9f0dd8946d0e58
