### ISSUE TITLE
Tooltip with app name

### ISSUE THREAD

**Issue by razvn** [tkint/kyro#2]
When the app names are long can't easly figure out which one is the one you look for:
![image](https://github.com/tkint/kyro/assets/745873/7d3a3aa0-d3fa-47c0-ac0f-9b60a8fcfbcf)

a tooltip with full app name would help in this case.

**Comment by tkint** [comment]
Hello,

Thank you for the report.
It has been solved in 81b5417e92156446dab8ede616fd1825d6fbdc10
